# -*- coding: utf-8 -*-
"""recommender_waterfall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ot-omwVXew9a003wCT46YXv1z2B62G_8

## 1. 导入必要的库
"""

# -*- coding: utf-8 -*-

import pandas as pd
import scipy.sparse as sps
import numpy as np
import os
import json
from tqdm import tqdm

from sklearn.model_selection import KFold

from RecSys_Course_AT_PoliMi.Data_manager.split_functions.split_train_validation_random_holdout import split_train_in_two_percentage_global_sample
from RecSys_Course_AT_PoliMi.Evaluation.Evaluator import EvaluatorHoldout
from RecSys_Course_AT_PoliMi.Recommenders.Recommender_import_list import *
from RecSys_Course_AT_PoliMi.Recommenders.KNN.ItemKNNCustomSimilarityRecommender import ItemKNNCustomSimilarityRecommender
from Recommenders.BaseRecommender import BaseRecommender

"""## 2. 项目配置与常量"""

# 数据文件路径
DATA_FOLDER = 'dataset'
DATA_TRAIN_PATH = os.path.join(DATA_FOLDER, 'data_train.csv')
DATA_TARGET_USERS_PATH = os.path.join(DATA_FOLDER, 'data_target_users_test.csv')
OUTPUT_FOLDER = 'temp_output'
MODEL_FOLDER = 'model_output'
SUBMISSION_FOLDER = 'temp_output' # 提交文件的保存目录

# 随机种子，用于确保实验结果的可复现性
RANDOM_SEED = 1234

# 本地验证时，训练集所占的百分比
TRAIN_PERCENTAGE = 0.80

# 评估时使用的推荐列表长度 (cutoff)
EVALUATION_CUTOFF = 20

# 设置全局随机种子
np.random.seed(RANDOM_SEED)

print("项目配置加载完成.")

"""## 3. 辅助函数

### 3.1 加载CSV数据文件，并将其转换为CSR格式的稀疏矩阵.
"""

def load_and_preprocess_data(file_path: str) -> sps.csr_matrix:
    """
    加载CSV数据文件，并将其转换为CSR格式的稀疏矩阵.
    """
    print("--- 正在加载和预处理数据... ---")
    df_train = pd.read_csv(file_path, dtype={'row': int, 'col': int})

    n_users = df_train['row'].max() + 1
    n_items = df_train['col'].max() + 1

    urm_all = sps.coo_matrix(
        ([1.0] * len(df_train['row']), (df_train['row'], df_train['col'])),
        shape=(n_users, n_items),
        dtype=float
    ).tocsr()
    print(f"数据加载完成. URM 维度: {urm_all.shape}")
    return urm_all

"""### 3.2 接收评估结果字典和模型名称，并以清晰的格式打印关键指标."""

def print_results_formatted(results_df, model_name: str = "Model"):
    """
    接收评估结果 DataFrame 和模型名称，并以清晰的格式打印关键指标.

    Args:
        results_df (pd.DataFrame): 来自 Evaluator.evaluateRecommender() 的结果DataFrame.
        model_name (str): 要打印的模型名称.
    """
    # 检查 DataFrame 是否为空，或者指定的 cutoff 值是否作为索引存在
    if results_df.empty or EVALUATION_CUTOFF not in results_df.index:
        print(f"--- 在 cutoff={EVALUATION_CUTOFF} 处没有找到 '{model_name}' 的评估结果 ---")
        return

    # 使用 .loc[] 通过索引名来选取我们关心的那一行数据
    # 这会返回一个 Pandas Series，其行为非常像一个字典
    res_series = results_df.loc[EVALUATION_CUTOFF]

    print(f"--- 模型评估结果: {model_name} ---")
    print(f"--------------------------------------------------")
    # 现在在一个 Pandas Series 上使用 .get() 方法，这是安全且正确的
    print(f"{f'RECALL@{EVALUATION_CUTOFF}':<25}: {res_series.get('RECALL', -1):.4f}   <-- 竞赛官方指标")
    print(f"{f'PRECISION@{EVALUATION_CUTOFF}':<25}: {res_series.get('PRECISION', -1):.4f}")
    print(f"{f'MAP@{EVALUATION_CUTOFF}':<25}: {res_series.get('MAP', -1):.4f}")
    print(f"{f'HIT_RATE@{EVALUATION_CUTOFF}':<25}: {res_series.get('HIT_RATE', -1):.4f}")
    print(f"{f'ITEM_COVERAGE@{EVALUATION_CUTOFF}':<25}: {res_series.get('COVERAGE_ITEM', -1):.4f}")
    print(f"{f'AVG_POPULARITY@{EVALUATION_CUTOFF}':<25}: {res_series.get('AVERAGE_POPULARITY', -1):.4f}")
    print(f"--------------------------------------------------\n")

"""### 3.4 读取模型"""

def load_best_model(recommender_class, urm_train, file_name, modelfile_path):
    """
    加载一个由超参数搜索脚本保存的最佳模型。
    """
    file_path = os.path.join(modelfile_path, file_name)

    print(f"--- 正在加载预训练模型: {file_name} ---")

    # 检查模型文件是否存在
    if not os.path.exists(file_path + ".zip"):
        print(f">>> 警告: 模型文件 '{file_path}.zip' 不存在!")
        print(">>> 请确保超参数优化已完成，并且文件名正确。")
        return None

    # 1. 初始化一个“空”的模型对象
    recommender_instance = recommender_class(urm_train)

    # 2. 调用 .load_model() 方法加载数据
    recommender_instance.load_model(folder_path=modelfile_path, file_name=file_name)

    print("模型加载成功！\n")
    return recommender_instance

"""## 4. 分割数据集
本节将加载数据，并将其分割为训练集和验证集，为模型评估做准备。
"""

# 加载数据
urm_all = load_and_preprocess_data(DATA_TRAIN_PATH)

# 分割数据用于本地验证
print("\n--- 正在分割数据用于本地验证... ---")
URM_train, URM_validation = split_train_in_two_percentage_global_sample(
    urm_all,
    train_percentage=TRAIN_PERCENTAGE
)
print("数据分割完成.")
print(f"训练集维度: {URM_train.shape}, 验证集维度: {URM_validation.shape}\n")


# 初始化评估器
evaluator_validation = EvaluatorHoldout(URM_validation, cutoff_list=[EVALUATION_CUTOFF])
print("评估器初始化完成.")

"""## 6. 模型融合

### 6c 瀑布融合

#### 6c.1 加载所有模型
"""

# MultiStageRecommender 类的定义保持不变
import numpy as np
import scipy.sparse as sps

class MultiStageRecommender(BaseRecommender):
    """
    一个实现了“召回与排序”架构的混合推荐器。

    - 召回模型 (candidate_generator): 一个快速、高召回率的模型，用于生成候选集。
    - 排序模型 (ranking_recommender): 一个精确、高准确率的模型，用于对候选集进行重新排序。
    """
    def __init__(self, urm_train, candidate_generator, ranking_recommender, candidate_cutoff=200):
        super(MultiStageRecommender, self).__init__(urm_train)
        self.candidate_generator = candidate_generator
        self.ranking_recommender = ranking_recommender
        self.candidate_cutoff = candidate_cutoff

    def _compute_item_score(self, user_id_array, items_to_compute=None):
        final_scores = np.full((len(user_id_array), self.n_items), -np.inf, dtype=np.float32)

        for user_index, user_id in enumerate(user_id_array):
            candidate_items = self.candidate_generator.recommend(user_id,
                                                                 cutoff=self.candidate_cutoff,
                                                                 remove_seen_flag=True)
            if len(candidate_items) == 0:
                continue

            ranking_scores = self.ranking_recommender._compute_item_score(np.array([user_id]),
                                                                         items_to_compute=candidate_items)
            final_scores[user_index, candidate_items] = ranking_scores[0, candidate_items]
        return final_scores

print("MultiStageRecommender 类已定义。")

class EnsembleCandidateGenerator(BaseRecommender):
    """
    一个用于“多路召回”的推荐器。
    它会调用内部的多个召回模型，并将它们的推荐结果合并、去重，形成一个更大的候选集。
    """
    def __init__(self, urm_train, recommenders):
        super(EnsembleCandidateGenerator, self).__init__(urm_train)
        self.recommenders = recommenders

    def recommend(self, user_id, cutoff=100, remove_seen_flag=True, items_to_compute=None, remove_top_pop_flag=False, remove_custom_items_flag=False, return_scores=False):
        # 注意：这里的 cutoff 是指 *每个* 内部推荐器要召回的数量

        # 使用集合(set)来自动处理去重
        candidate_items_set = set()

        # 遍历所有的召回模型
        for recommender in self.recommenders:
            # 获取当前模型的推荐结果
            partial_recs = recommender.recommend(user_id,
                                                 cutoff=cutoff,
                                                 remove_seen_flag=remove_seen_flag)

            # 将结果添加到集合中
            candidate_items_set.update(partial_recs)

        # 将集合转换为列表返回
        # 注意：最终的候选集大小会小于 (模型数量 * cutoff)，具体取决于各模型结果的重合度
        return list(candidate_items_set)

    # 这个类不需要实现 _compute_item_score，因为它只用于生成候选列表
    def _compute_item_score(self, user_id_array, items_to_compute=None):
        raise NotImplementedError("EnsembleCandidateGenerator does not support score computation.")

class FusedRanker(BaseRecommender):
    """
    终极健壮的分数融合排序器：
    1. 健壮地处理分数归一化时的“全零”行。
    2. 使用 np.nan_to_num 清理上游模型可能返回的 NaN 或 inf 值。
    """
    def __init__(self, urm_train, recommenders, weights=None):
        super(FusedRanker, self).__init__(urm_train)
        self.recommenders = recommenders
        self.weights = weights if weights is not None else [1/len(recommenders)] * len(recommenders)

    def _normalize_scores(self, scores):
        if sps.issparse(scores):
            scores = scores.toarray()

        for i in range(scores.shape[0]):
            row = scores[i]
            # 仅对有限数值进行计算，忽略 inf
            finite_vals = row[np.isfinite(row)]
            if len(finite_vals) == 0:
                # 如果行中所有值都是 inf 或 nan
                scores[i] = 0.0
                continue

            max_val = np.max(finite_vals)
            min_val = np.min(finite_vals)
            denominator = max_val - min_val

            if denominator == 0:
                scores[i] = 0.0
            else:
                scores[i] = (row - min_val) / denominator

        return scores

    def _compute_item_score(self, user_id_array, items_to_compute=None):
        final_scores = np.zeros((len(user_id_array), self.n_items), dtype=np.float32)

        for i, recommender in enumerate(self.recommenders):
            current_scores = recommender._compute_item_score(user_id_array, items_to_compute)

            normalized_scores = self._normalize_scores(current_scores)

            # 关键步骤：清理任何可能存在的 NaN 或 inf
            # 这可以防止它们污染最终的分数
            sanitized_scores = np.nan_to_num(normalized_scores)

            final_scores += self.weights[i] * sanitized_scores

        return final_scores

print("EnsembleCandidateGenerator 类已定义。")


# --- 1. 加载和准备所有用于网格搜索的候选模型 (在验证集上) ---
VALIDATION_MODEL_FOLDER = "temp_output"
print(f"\n--- 正在从 '{VALIDATION_MODEL_FOLDER}' 文件夹加载所有用于网格搜索的候选模型... ---")

# --- 准备排序模型候选人 (在 URM_train 上训练) ---
print("--- 准备排序模型 ---")
recommender_slim_val = load_best_model(
    recommender_class=SLIMElasticNetRecommender,
    urm_train=URM_train,
    file_name="SLIMElasticNetRecommender_best_model",
    modelfile_path=VALIDATION_MODEL_FOLDER
)
recommender_ials_val = load_best_model(
    recommender_class=IALSRecommender,
    urm_train=URM_train,
    file_name="IALSRecommender_best_model",
    modelfile_path=VALIDATION_MODEL_FOLDER
)

# --- 准备召回模型候选人 (在 URM_train 上训练) ---
# 注意：您的代码中没有提供 EASE_R 在 temp_output 的模型，我们假设它存在
# 如果不存在，您需要先运行EASE_R的超参数搜索
print("\n--- 准备召回模型 ---")
recommender_easer_val = load_best_model(
    recommender_class=EASE_R_Recommender, # 假设您有EASE_R的模型
    urm_train=URM_train,
    file_name="EASE_R_Recommender_best_model", # 假设这是它的文件名
    modelfile_path=VALIDATION_MODEL_FOLDER
)

recommender_itemknn_val = load_best_model(
    recommender_class=UserKNNCFRecommender, # 假设您有EASE_R的模型
    urm_train=URM_train,
    file_name="UserKNNCFRecommender_jaccard_best_model", # 假设这是它的文件名
    modelfile_path=VALIDATION_MODEL_FOLDER
)

"""#### 6c.2 在本地验证集上寻找最佳召回"""

# --- 2. 在本地验证集上进行网格搜索 (更新版) ---

models_ready = all([recommender_slim_val, recommender_ials_val, recommender_easer_val, recommender_itemknn_val])

if models_ready:
    # --- 1. 定义召回层候选人 (Candidate Generators) ---

    # 单模型召回
    cand_knn = recommender_itemknn_val
    cand_ials = recommender_ials_val
    cand_easer = recommender_easer_val

    # 多路召回 (并集)
    cand_ensemble_knn_ials = EnsembleCandidateGenerator(URM_train, [recommender_itemknn_val, recommender_ials_val])
    cand_ensemble_knn_easer = EnsembleCandidateGenerator(URM_train, [recommender_itemknn_val, recommender_easer_val])
    cand_ensemble_ials_easer = EnsembleCandidateGenerator(URM_train, [recommender_ials_val, recommender_easer_val])
    # 终极三合一召回
    cand_ensemble_all = EnsembleCandidateGenerator(URM_train, [recommender_itemknn_val, recommender_ials_val, recommender_easer_val])

    # 将所有召回器放入字典，方便遍历
    candidate_generators = {
        "C_ItemKNN": cand_knn,
        "C_IALS": cand_ials,
        "C_EASER": cand_easer,
        "C_Ens_KnnIals": cand_ensemble_knn_ials,
        "C_Ens_KnnEaser": cand_ensemble_knn_easer,
        "C_Ens_IalsEaser": cand_ensemble_ials_easer,
        "C_Ens_All": cand_ensemble_all,
    }
    print(f"已定义 {len(candidate_generators)} 种召回策略。")

    # --- 2. 定义排序层候选人 (Rankers) ---

    # 单模型排序
    rank_slim = recommender_slim_val
    rank_easer = recommender_easer_val
    rank_ials = recommender_ials_val

    # 分数融合排序 (这里我们使用平均融合，您也可以后续加入权重搜索)
    rank_fused_slim_easer = FusedRanker(URM_train, [recommender_slim_val, recommender_easer_val])
    rank_fused_slim_ials = FusedRanker(URM_train, [recommender_slim_val, recommender_ials_val])

    # 将所有排序器放入字典
    rankers = {
        "R_SLIM": rank_slim,
        "R_EASER": rank_easer,
        "R_IALS": rank_ials,
        "R_Fused_SlimEaser": rank_fused_slim_easer,
        "R_Fused_SlimIals": rank_fused_slim_ials,
    }
    print(f"已定义 {len(rankers)} 种排序策略。")

    # --- 3. 定义候选集大小 ---
    candidate_cutoffs = [100, 200, 300, 400]
    print(f"将测试 {len(candidate_cutoffs)} 种候选集大小。")

    # --- 开始全自动、大范围的网格搜索 ---

    best_recall = 0.0
    best_combination = {}
    results_log = []

    total_combinations = len(candidate_generators) * len(rankers) * len(candidate_cutoffs)
    print(f"\n--- 即将开始测试 {total_combinations} 种组合，请耐心等待... ---")

    pbar = tqdm(total=total_combinations, desc="网格搜索进度")

    for cand_name, cand_model in candidate_generators.items():
        for rank_name, rank_model in rankers.items():
            # 理论上，排序模型不应与召回模型中的任何一个相同，但我们先测试所有组合
            # if rank_name in cand_name:
            #     pbar.update(len(candidate_cutoffs))
            #     continue

            for k in candidate_cutoffs:

                # 构建“召回与排序”推荐器
                multistage_recommender = MultiStageRecommender(URM_train,
                                                               candidate_generator=cand_model,
                                                               ranking_recommender=rank_model,
                                                               candidate_cutoff=k)

                # 评估
                results_df, _ = evaluator_validation.evaluateRecommender(multistage_recommender)
                current_recall = results_df.loc[EVALUATION_CUTOFF].get('RECALL', 0.0)

                # 记录结果
                current_config = {
                    "Recall_Strategy": cand_name,
                    "Ranking_Strategy": rank_name,
                    "K": k,
                    "Recall@20": current_recall
                }
                results_log.append(current_config)

                if current_recall > best_recall:
                    best_recall = current_recall
                    best_combination = current_config
                    print(f"\n🔥🔥🔥 新的最佳组合! Recall: {best_recall:.5f} | Config: {cand_name} -> {rank_name} (K={k})")

                pbar.update(1)

    pbar.close()

    # --- 结果汇总 ---
    print("\n\n--- 网格搜索完成！---")
    print("找到的最佳组合如下:")
    print(json.dumps(best_combination, indent=4, ensure_ascii=False))

    # 将所有结果转换为DataFrame并按Recall排序，方便分析
    results_df_summary = pd.DataFrame(results_log)
    print("\n--- 所有组合性能排行 Top 10 ---")
    print(results_df_summary.sort_values(by="Recall@20", ascending=False).head(10))

    # 建议保存完整日志
    results_df_summary.to_csv("grid_search_log.csv", index=False)
    print("\n完整日志已保存至 grid_search_log.csv")

"""#### 6c.3 生成最终提交文件"""