# -*- coding: utf-8 -*-
"""LoRasim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGP8WB0eE0_yZLws6Id9Q_UYmMXKW-ca

## **Setup the environment**
"""

! wget https://www.lancaster.ac.uk/scc/sites/lora/lorasim-20170710.tgz
! tar -xvf lorasim-20170710.tgz

!sudo apt-get install python2 && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py && python2 get-pip.py && rm get-pip.py
!sudo apt install python-tk
!pip2 install -r 'lorasim/requirements.txt'

"""## **Play with the simulator**

### **Import libraries**
"""

import os
import pandas as pd
import math

"""### **Execute simulations**"""

# SN1: 0 # SN2: 2 # SN3: 4 # SN4: 3 # SN5: 5
import subprocess

def simulate(n_nodes, tx_rate, exp, duration, collition):
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"
    # Use subprocess.run to execute the command and capture output
    result = subprocess.run(
        [
            "python2",
            "lorasim/loraDir.py",
            str(int(n_nodes)),
            str(int(tx_rate)),
            str(int(exp)),
            str(int(duration)),
            str(int(collition)),
        ],
        env=env,
        capture_output=True,
        text=True,  # Capture output as text
    )

    # Print the output
    # print(result.stdout)
    # print(result.stderr)

# Der in aloha defined as S/G = e^(-2G)
def aloha_der(n_nodes,t):
    rate = 1e-6
    return math.exp(-2 * n_nodes * rate * t)

"""Fig. 5"""

duration = 86400000
tx_rate = 1e6
for n_nodes in [1,50,100] + list(range(200,1000,100)) + list(range(1000,1800,200)):
  print(f"Simulating {n_nodes} nodes")
  simulate(n_nodes, tx_rate, 4, duration, 1)
  simulate(n_nodes, tx_rate, 3, duration, 1)
  simulate(n_nodes, tx_rate, 5, duration, 1)

data = pd.read_csv("/content/exp4.dat",sep=" ")
data2 = pd.read_csv("/content/exp3.dat",sep=" ")
data3 = pd.read_csv("/content/exp5.dat",sep=" ")

data["der"] = (data["nrTransmissions"] - data["nrCollisions"]) / data["nrTransmissions"]
data2["der"] = (data2["nrTransmissions"] - data2["nrCollisions"]) / data2["nrTransmissions"]
data3["der"] = (data3["nrTransmissions"] - data3["nrCollisions"]) / data3["nrTransmissions"]

import matplotlib
import matplotlib.pyplot as plt

plt.plot(
    data["#nrNodes"],
    data["der"],
    label="SN3(Static)",
    marker='s',
    linestyle='-',
    color='skyblue',
    markersize=4,
    linewidth=1,
)
plt.plot(
    data2["#nrNodes"],
    data2["der"],
    label="SN4(Dynamic, min airtime)",
    marker='o',
    linestyle='-',
    color='green',
    markersize=4,
    linewidth=1,
)
plt.plot(
    data3["#nrNodes"],
    data3["der"],
    label="SN5(Dynamic, min airtime & TP)",
    marker='o',
    linestyle='-',
    color='orange',
    markersize=4,
    markerfacecolor='none',
    linewidth=1,
)
plt.xlabel("Number of nodes")
plt.ylabel("Data Extraction Rate")
plt.ylim(0, 1.1)
plt.legend()
plt.grid()
plt.show()

"""Fig.7"""

# SN1: 0 # SN2: 2 # SN3: 4 # SN4: 3 # SN5: 5
import subprocess

def simulate2(n_nodes, tx_rate, exp, duration, station, collition):
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"
    # Use subprocess.run to execute the command and capture output
    result = subprocess.run(
        [
            "python2",
            "lorasim/loraDirMulBS.py",
            str(int(n_nodes)),
            str(int(tx_rate)),
            str(int(exp)),
            str(int(duration)),
            str(int(station)),
            str(int(collition)),
        ],
        env=env,
        capture_output=True,
        text=True,  # Capture output as text
    )

duration = 86400000
tx_rate = 1e6

for n_nodes in [1,100] + list(range(200,1000,100)) + list(range(1000,1800,200)):
  print(f"Simulating {n_nodes} nodes")
  simulate2(n_nodes, tx_rate, 0, duration, 1, 1)
  simulate2(n_nodes, tx_rate, 0, duration, 2, 1)
  simulate2(n_nodes, tx_rate, 0, duration, 3, 1)
  simulate2(n_nodes, tx_rate, 0, duration, 4, 1)
  simulate2(n_nodes, tx_rate, 0, duration, 8, 1)
  simulate2(n_nodes, tx_rate, 0, duration, 24, 1)

data_7_1 = pd.read_csv("/content/exp0BS1.dat", sep=" ")
data_7_1['nrNodes'], data_7_1['DER'] = data_7_1['#'], data_7_1['nrNodes']
data_7_1 = data_7_1.drop('#', axis=1)
data_7_2 = pd.read_csv("/content/exp0BS2.dat", sep=" ")
data_7_2['nrNodes'], data_7_2['DER'] = data_7_2['#'], data_7_2['nrNodes']
data_7_2 = data_7_2.drop('#', axis=1)
data_7_3 = pd.read_csv("/content/exp0BS3.dat",sep=" ")
data_7_3['nrNodes'], data_7_3['DER'] = data_7_3['#'], data_7_3['nrNodes']
data_7_3 = data_7_3.drop('#', axis=1)
data_7_4 = pd.read_csv("/content/exp0BS4.dat",sep=" ")
data_7_4['nrNodes'], data_7_4['DER'] = data_7_4['#'], data_7_4['nrNodes']
data_7_4 = data_7_4.drop('#', axis=1)
data_7_5 = pd.read_csv("/content/exp0BS8.dat",sep=" ")
data_7_5['nrNodes'], data_7_5['DER'] = data_7_5['#'], data_7_5['nrNodes']
data_7_5 = data_7_5.drop('#', axis=1)
data_7_6 = pd.read_csv("/content/exp0BS24.dat",sep=" ")
data_7_6['nrNodes'], data_7_6['DER'] = data_7_6['#'], data_7_6['nrNodes']
data_7_6 = data_7_6.drop('#', axis=1)

import matplotlib
import matplotlib.pyplot as plt
plt.plot(
    data_7_6["nrNodes"],
    data_7_6["DER"],
    label="24 sink",
    marker='o',
    linestyle='-',
    color='skyblue',
    markersize=4,
    markerfacecolor='none',
    linewidth=1,
)
plt.plot(
    data_7_5["nrNodes"],
    data_7_5["DER"],
    label="8 sink",
    marker='s',
    linestyle='-',
    color='red',
    markersize=4,
    linewidth=1,
)

plt.plot(
    data_7_4["nrNodes"],
    data_7_4["DER"],
    label="4 sink",
    marker='s',
    linestyle='-',
    color='purple',
    markersize=4,
    markerfacecolor='none',
    linewidth=1,
)
plt.plot(
    data_7_3["nrNodes"],
    data_7_3["DER"],
    label="3 sink",
    marker='*',
    linestyle='-',
    color='orange',
    markersize=4,
    linewidth=1,
)

plt.plot(
    data_7_2["nrNodes"],
    data_7_2["DER"],
    label="2 sink",
    marker='o',
    linestyle='-',
    color='green',
    markersize=4,
    linewidth=1,
)

plt.plot(
    data_7_1["nrNodes"],
    data_7_1["DER"],
    label="1 sink",
    marker='+',
    linestyle='-',
    color='blue',
    markersize=4,
    linewidth=1,
)

plt.xlabel("Number of nodes")
plt.ylabel("Data Extraction Rate")
plt.ylim(0, 1.1)
plt.legend()
plt.grid()
plt.show()

# clear
import os
import glob

# Get all .dat files in the /content directory
dat_files = glob.glob('/content/*.dat')

# Delete one by one
for file in dat_files:
    os.remove(file)
    print(f"Deleted: {file}")

print(f"Deleted {len(dat_files)} .dat files")